name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven 
      run: mvn -B package --file pom.xml

    - name: Build Docker Image
      run: docker build -t mirakiii/hello-world-java:0.0.1.Release .

    - name: Push Docker Image
      run: docker push mirakiii/hello-world-java-maven:0.0.1.Release

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push mirakiii/hello-world-java:0.0.1.Release
      
